import { prisma } from "@/lib/prisma";
import { foodId, exerciseId } from "@/lib/slug";
import {
  DayMealPlan,
  NutritionTargets,
  WorkoutDayPlan,
} from "@/lib/types";

// Persiste os planos gerados para um usuário.
// Requer o catálogo semeado (npm run seed) para que os FKs de FoodItem /
// Exercise existam.

/** Primeiro inteiro de uma string de reps ("8-12" -> 8, "15-20 min" -> 15). */
function parseReps(reps: string): number {
  const m = reps.match(/\d+/);
  return m ? parseInt(m[0], 10) : 10;
}

/** Salva metas diárias no perfil do usuário. */
export async function saveTargets(userId: string, t: NutritionTargets) {
  await prisma.profile.update({
    where: { userId },
    data: {
      calorieTarget: t.calorieTarget,
      proteinTargetG: t.proteinTargetG,
      waterTargetMl: t.waterTargetMl,
      fiberTargetG: t.fiberTargetG,
    },
  });
}

/** Salva um plano alimentar semanal. Arquiva planos ativos anteriores. */
export async function saveMealPlan(userId: string, week: DayMealPlan[]) {
  await prisma.mealPlan.updateMany({
    where: { userId, status: "active" },
    data: { status: "archived" },
  });

  const from = new Date();
  const to = new Date();
  to.setDate(to.getDate() + 7);

  return prisma.mealPlan.create({
    data: {
      userId,
      name: `Plano ${from.toLocaleDateString("pt-BR")}`,
      status: "active",
      fromDate: from,
      toDate: to,
      autoGenerated: true,
      meals: {
        create: week.flatMap((day) =>
          day.meals.map((meal) => ({
            dayOfWeek: day.dayOfWeek,
            mealType: meal.mealType,
            items: {
              create: meal.items.map((item) => ({
                foodItemId: foodId(item.food),
                quantityG: item.quantityG,
              })),
            },
          }))
        ),
      },
    },
  });
}

/** Salva um plano de treino semanal. Arquiva planos ativos anteriores. */
export async function saveWorkoutPlan(userId: string, week: WorkoutDayPlan[]) {
  await prisma.workoutPlan.updateMany({
    where: { userId, status: "active" },
    data: { status: "archived" },
  });

  const from = new Date();
  const to = new Date();
  to.setDate(to.getDate() + 7);

  return prisma.workoutPlan.create({
    data: {
      userId,
      name: `Treino ${from.toLocaleDateString("pt-BR")}`,
      status: "active",
      fromDate: from,
      toDate: to,
      autoGenerated: true,
      days: {
        create: week.map((day) => ({
          dayOfWeek: day.dayOfWeek,
          focus: day.focus,
          exercises: {
            create: day.exercises.map((ex, i) => ({
              exerciseId: exerciseId(ex.exercise),
              order: i + 1,
              sets: ex.sets,
              reps: parseReps(ex.reps),
              restSec: ex.restSec,
            })),
          },
        })),
      },
    },
  });
}
